bookname: Onestop-LT
booktitle: ワンストップLT
aut: []
language: ja
toc: true
rights: (C) 2023　エンジニアの登壇を応援する会
colophon: true
history:
  - - 2023-11-25　初版
pbl: エンジニアの登壇を応援する会
edt: 親方Project　@oyakata2438
date: '2023-11-25'
secnolevel: 3
titlepage: true
review_version: 3
texstyle:
  - reviewmacro
texdocumentclass:
  - review-jsbook
  - >-
    media=ebook,paper=b5,serial_pagination=true,hiddenfolio=nikko-pc,openany,fontsize=10pt,baselineskip=15.4pt,line_length=44zw,number_of_lines=40,head_space=18mm,headsep=3mm,headheight=5mm,footskip=10mm
